name: Collect Workflow Telemetry

on:
  push:
  pull_request:

permissions:
  pull-requests: write

jobs:
  workflow-telemetry-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
