name: VM Resource Telemetry

on:
  push:
  pull_request:

jobs:
  system-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Capture VM Metrics
        uses: self-actuated/vmmeter-action@v1
