name: Java CI with Dummy Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload dummy JaCoCo report XML
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: coverage.cobertura.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.cobertura.xml
        flags: unittests
        name: codecov-jacoco
        fail_ci_if_error: true
